### ISSUE TITLE
Questions for task 2

### ISSUE THREAD

**Issue by LuKunze** [Schubisu/machinelearning_in_r#1]
I have completed the code for task 2. There are only some questions left:

1. How do we set setwd() that Puchalla can run the code and has the data avaiblabe?

2. I have also used now the confusionMatrix() demand from the caret-package. But unfortunately the table in this outcome is labeled the other way around "0" for event, etc. Therefore the numbers for sensitivity/specificity are swapped. Should we leave it out then? Can anybody fix this? I mean..we have the right results, but would be nice :D

3. Please check the interpretation for questions 2.7 / 2.8 - or we will discuss it at the group meeting. I was not quite sure with this.

**Comment by Lu-Ma-Lu** [comment]
1. In RStudio, you can click “Tools” -> “Import Dataset” -> “From Web URL” and a dialog will pop up asking you for a URL. Paste a URL into the dialog box  and click “OK”. A nice little window pops up and allows you to specify how the data should be read and what name the object should be given in R. When you click “Import”, the data is read in and some code appears in the console. What this interface does is download the data to a temporary file in a temporary folder and then read it in. The downloaded data file persists on your hard drive as long as your R session lasts, but disappears as soon as your R session ends. (We would have to upload the data into here and copy the code into the file therefore).

**Comment by Schubisu** [comment]
concerning 1)
I don't think that it's necessary to `setwd` at all, in fact it's rather confusing because these are local directories on our machines. We can rather put instructions into the comments to set the current working directory to the folder of this project.

I will have a look at the other tasks later today or tomorrow.

**Comment by LuKunze** [comment]
2) I corrected the demands for the confusionMatrix and the results respectively.
